Web/MyHotelWebsite.Web/Areas/Administration/Controllers/DishesController.cs
namespace MyHotelWebsite.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using MyHotelWebsite.Common;
    using MyHotelWebsite.Data.Models.Enums;
    using MyHotelWebsite.Services.Data;
    using MyHotelWebsite.Web.ViewModels.Administration.Dishes;
    using MyHotelWebsite.Web.ViewModels.Administration.Enums;
    using MyHotelWebsite.Web.ViewModels.Dishes;

    [Authorize(Roles = GlobalConstants.HotelManagerRoleName + ", " + GlobalConstants.ChefRoleName)]
    public class DishesController : AdministrationController
    {
        private readonly IDishesService dishesService;
        private readonly IWebHostEnvironment environment;

        public DishesController(IDishesService dishesService, IWebHostEnvironment environment)
        {
            this.dishesService = dishesService;
            this.environment = environment;
        }

        public async Task<IActionResult> All(int id = 1)
        {
            if (id < 1)
            {
                return this.BadRequest();
            }

            const int DishesPerPage = 12;
            var model = new AllDishViewModel
            {
                ItemsPerPage = DishesPerPage,
                AllEntitiesCount = await this.dishesService.GetCountAsync(),
                Dishes = await this.dishesService.GetAllDishesAsync<SingleDishViewModel>(id, DishesPerPage),
                PageNumber = id,
            };
            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(model);
        }

        public async Task<IActionResult> ByCategory(DishCategory dishCategory, bool isReady, bool? isInStock, DishSorting sorting, int id = 1)
        {
            if (id < 1)
            {
                return this.BadRequest();
            }

            const int DishesPerPage = 12;

            var dishesWithFilter = await this.dishesService.GetDishesByDishCategoryAsync<SingleDishViewModel>(id, dishCategory, sorting, isInStock, isReady, DishesPerPage);
            var model = new DishByCategoryViewModel
            {
                ItemsPerPage = DishesPerPage,
                AllEntitiesCount = await this.dishesService.GetCountOfDishesByCategoryAsync(isInStock, isReady, dishCategory, sorting),
                Dishes = dishesWithFilter,
                PageNumber = id,
                DishCategory = dishCategory.ToString(),
                IsReady = isReady,
                IsInStock = isInStock,
                Sorting = sorting,
            };
            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(model);
        }

        public IActionResult Create()
        {
            var model = new CreateDishViewModel();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateDishViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var staffId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {
                await this.dishesService.AddDishAsync(model, staffId, $"{this.environment.WebRootPath}/images");
                this.TempData["Message"] = "Dish added successfully.";
            }
            catch (Exception)
            {
                this.ModelState.AddModelError(string.Empty, "Could not add this dish");
                return this.View(model);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (!await this.dishesService.DoesDishExistsAsync(id))
            {
                return this.RedirectToAction(nameof(this.All));
            }

            await this.dishesService.DeleteDishAsync(id);
            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (!await this.dishesService.DoesDishExistsAsync(id))
            {
                return this.RedirectToAction(nameof(this.All));
            }

            var model = await this.dishesService.DishDetailsByIdAsync<EditDishViewModel>(id);
            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditDishViewModel model, IFormFile? file)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var staffId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
            {
                await this.dishesService.EditDishAsync(model, id, staffId, $"{this.environment.WebRootPath}/images", file);
                this.TempData["Message"] = "Dish changed successfully.";
            }
            catch (Exception)
            {
                this.ModelState.AddModelError(string.Empty, "Could not edit this dish");
                this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
                return this.View(model);
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> Prepare(string id)
        {
            try
            {
                await this.dishesService.PrepareDishAsync(id);
                this.TempData["Message"] = "Dish prepared successfully.";
            }
            catch (Exception)
            {
                this.TempData["Error"] = "Could not prepare this dish";
                this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult Search()
        {
            this.DropDownReBind();
            return this.View();
        }

        private void DropDownReBind()
        {
            List<SelectListItem> boolYesOrNo = new List<SelectListItem>();

            boolYesOrNo.Add(new SelectListItem
            {
                Text = "Yes",
                Value = true.ToString(),
            });
            boolYesOrNo.Add(new SelectListItem
            {
                Text = "No",
                Value = false.ToString(),
            });

            this.ViewData["boolYesOrNo"] = boolYesOrNo;
        }
    }
}

Web/MyHotelWebsite.Web/Controllers/DishesController.cs
namespace MyHotelWebsite.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using MyHotelWebsite.Data.Models.Enums;
    using MyHotelWebsite.Services.Data;
    using MyHotelWebsite.Web.ViewModels.Dishes;

    public class DishesController : BaseController
    {
        private readonly IDishesService dishesService;

        public DishesController(IDishesService dishesService)
        {
            this.dishesService = dishesService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public async Task<IActionResult> All(int id = 1)
        {
            if (id < 1)
            {
                return this.BadRequest();
            }

            const int DishesPerPage = 12;
            var model = new AllDishViewModel
            {
                ItemsPerPage = DishesPerPage,
                AllEntitiesCount = await this.dishesService.GetCountAsync(),
                Dishes = await this.dishesService.GetAllDishesAsync<SingleDishViewModel>(id, DishesPerPage),
                PageNumber = id,
            };
            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(model);
        }

        public async Task<IActionResult> ByNameAndCategory(string name, DishCategory dishCategory, int id = 1)
        {
            if (id < 1)
            {
                return this.BadRequest();
            }

            const int DishesPerPage = 12;

            var dishesWithFilter = await this.dishesService.SearchDishesByNameAndCategoryAsync<SingleDishViewModel>(id, name, dishCategory, DishesPerPage);
            var model = new DishByNameAndCategoryViewModel
            {
                ItemsPerPage = DishesPerPage,
                AllEntitiesCount = await this.dishesService.GetCountOfDishesByNameAndCategoryAsync(name, dishCategory),
                Dishes = dishesWithFilter,
                PageNumber = id,
                DishCategory = dishCategory.ToString(),
            };
            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(model);
        }
    }
}

Web/MyHotelWebsite.Web/Views/Dishes/All.cshtml
@using MyHotelWebsite.Web.ViewModels.Dishes
@model AllDishViewModel

<body>
    <div id="page">
        <section class="image-head-wrapper-dining-all">
            <div class="inner-wrapper">
                <h1>All Dishes</h1>
            </div>
        </section>
            @{ await Html.RenderPartialAsync("_SearchDishesPartial", new SingleDishViewModel()); }
        <div class="row">
        <partial name="_SingleDishPartial" />
        </div>
        <partial name="_PagingPartial" />
    </div>
</body>

Web/MyHotelWebsite.Web/Views/Dishes/ByNameAndCategory.cshtml
@using MyHotelWebsite.Web.ViewModels.Dishes

@model DishByNameAndCategoryViewModel

<body>
    <div id="page">
        <div class="clearfix"></div>
        <div class="row">
            @if (!Model.Dishes.Any())
            {
                <div class="col-12 text-center">
                    <h2>Nothing found</h2>
                    <br />
                </div>
            }
            else
            {
                <partial name="_SingleDishByNameAndCategoryPartial" />
                <br />
                <partial name="_PagingDishesByNameAndCategoryPartial" model="@Model" />
            }
            <form method="post" asp-controller="Dishes" asp-action="All">
                <div class="text-center"><button type="submit" class="btn btn-danger wrn-btn" style="margin-left:10px">Search Again</button></div>
            </form>
            
        </div>
    </div>
</body>

Web/MyHotelWebsite.Web/Views/Dishes/Index.cshtml
<!--Template Name: vacayhome
File Name: news.html
Author Name: ThemeVault
Author URI: http://www.themevault.net/
License URI: http://www.themevault.net/license/-->

<body>
    <div id="page">
       
        <section class="image-head-wrapper-dining">
            <div class="inner-wrapper">
                <h1>Dining</h1>
            </div>
        </section>
        <div class="clearfix"></div>

        <section class="gallery-block gallery-front">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 remove-padd-right">
                        <div class="side-A">
                            <div class="product-thumb">
                                <div class="image">
                                    <img alt="image" class="img-responsive" src="~/images/Dining-drinks.png">
                                </div>
                            </div>
                        </div>
                        <div class="side-B">
                            <div class="product-desc-side">
                                <h3>Drinks</h3>
                                <p>Feel fresh and well every day: a selection of soft drinks and teas, as well as South Tyrolean apples in the hotel's Balance SPA. Also alcohol for those who prefer it. Each guest is welcomed with drink upon arrival.</p>
                            </div>
                        </div>
                    </div>  

                    <div class="col-lg-6 col-md-6 col-sm-6col-xs-12 remove-padd-left">
                        <div class="side-A">
                            <div class="product-thumb">
                                <div class="image">
                                    <img src="~/images/Dining-gourmets.png" class="img-responsive" alt="image">
                                </div>
                            </div>
                        </div>
                        <div class="side-B">
                            <div class="product-desc-side">
                                <h3>Gourmet</h3>
                                <p>Sumptuous gourmet breakfast buffet: making sure every day gets off to the perfect start and daily gourmet cheese buffet with fruity chutneys and fresh fruit.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="gallery-block gallery-front">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 remove-padd-right">
                        <div class="side-A">
                            <div class="product-desc-side">
                                <h3>Appetizers</h3>
                                <p>
                                    Tasting sessions with homemade delicacies and specialties - from South Tyrol, Italy and typical Stubai specialities.
                                </p>
                            </div>
                        </div>

                        <div class="side-B">
                            <div class="product-thumb">
                                <div class="image txt-rgt">
                                    <img alt="imaga" class="img-responsive" src="~/images/Dining-appetizers.png">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6col-xs-12 remove-padd-left">
                        <div class="side-A">
                            <div class="product-desc-side">
                                <h3>Salads</h3>
                                <p>Fresh salad buffet with dressings and salad accompaniments of our guests' choice.</p>
                            </div>
                        </div>

                        <div class="side-B">
                            <div class="product-thumb txt-rgt">
                                <div class="image">
                                   <img alt="imaga" class="img-responsive" src="~/images/Dining-salads.png">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="gallery-block gallery-front">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 remove-padd-right">
                        <div class="side-A">
                            <div class="product-thumb">
                                <div class="image">
                                    <img alt="image" class="img-responsive" src="~/images/Dining-maincourses.png">
                                </div>
                            </div>
                        </div>
                        <div class="side-B">
                            <div class="product-desc-side">
                                <h3>Main courses</h3>
                                <p>Evening five-course menu – light, carefully chosen ingredients and consciously prepared food, serviced in the stylish ambience of candlelight and with wine specialist advice.</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-6col-xs-12 remove-padd-left">
                        <div class="side-A">
                            <div class="product-thumb">
                                <div class="image">
                                    <img src="~/images/Dining-desserts.png" class="img-responsive" alt="image">
                                </div>
                            </div>
                        </div>
                        <div class="side-B">
                            <div class="product-desc-side">
                                <h3>Desserts</h3>
                                <p>Sweet tooth buffet with homemade desserts - tasty, healthy and unique.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <hr />

        <section>
            <div class="container justify-content-center">
                <div class="h-100 d-flex align-items-center justify-content-center">
                    <form method="post" asp-controller="Dishes" asp-action="All">
                        <div class="text-center"><button type="submit" class="book-now-btn">See all and make an order</button></div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</body>