Web/MyHotelWebsite.Web/Areas/Guest/Controllers/ShoppingCartsController.cs
namespace MyHotelWebsite.Web.Areas.Guest.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using MyHotelWebsite.Common;
    using MyHotelWebsite.Services.Data;
    using MyHotelWebsite.Web.Controllers;
    using MyHotelWebsite.Web.ViewModels.Dishes;
    using MyHotelWebsite.Web.ViewModels.Guests.ShoppingCarts;

    [Area("Guest")]
    [Authorize(Roles = GlobalConstants.GuestRoleName)]
    public class ShoppingCartsController : BaseController
    {
        private readonly IDishesService dishesService;
        private readonly IShoppingCartsService shoppingCartsService;
        private readonly IOrdersService ordersService;

        public ShoppingCartsController(IDishesService dishesService, IShoppingCartsService shoppingCartsService, IOrdersService ordersService)
        {
            this.dishesService = dishesService;
            this.shoppingCartsService = shoppingCartsService;
            this.ordersService = ordersService;
        }

        [BindProperty]
        public AllShoppingCartsOfOneUserViewModel AllShoppingCartModel { get; set; }

        public async Task<IActionResult> Buy(string id)
        {
            if (!await this.dishesService.DoesDishExistsAsync(id))
            {
                return this.RedirectToAction("All", "Dishes", new { area = string.Empty });
            }

            var model = new SingleShoppingCartViewModel
            {
                DishId = id,
                Dish = await this.dishesService.DishDetailsByIdAsync<SingleDishViewModel>(id),
                Count = 1,
                ApplicationUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
            };
            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Buy(SingleShoppingCartViewModel shoppingCart)
        {
            int currentDishQuantity = await this.dishesService.DishQuantityInStockAsync(shoppingCart.DishId);
            if (currentDishQuantity < 1)
            {
                this.TempData["Error"] = "This dish is not in stock. Please choose another one.";
                return this.RedirectToAction("All", "Dishes", new { area = string.Empty });
            }
            else
            {
                bool dishAlreadyIsInTheShoppingCart = await this.shoppingCartsService.IsDishAlreadyInTheShoppingCartOfThatUserAsync(shoppingCart.DishId, shoppingCart.ApplicationUserId);
                List<SingleShoppingCartViewModel> itemsInTheShoppingCart;

                if (!dishAlreadyIsInTheShoppingCart)
                {
                    await this.shoppingCartsService.AddDishInTheShoppingCartAsync(shoppingCart);
                    this.TempData["Message"] = "Dish added successfully to shopping cart";
                }
                else
                {
                    await this.shoppingCartsService.UpdateDishCountInTheShoppingCartAsync(shoppingCart.DishId, shoppingCart.ApplicationUserId, shoppingCart.Count);
                }

                itemsInTheShoppingCart = await this.shoppingCartsService.GetAllSingleShoppingCartsOfTheUserAsync(shoppingCart.ApplicationUserId);
                this.HttpContext.Session.SetInt32(GlobalConstants.SessionCart, itemsInTheShoppingCart.Count);
            }

            return this.RedirectToAction("All", "Dishes", new { area = string.Empty });
        }

        public async Task<IActionResult> Index()
        {
            this.AllShoppingCartModel = new();
            string applicationUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!string.IsNullOrEmpty(applicationUserId))
            {
                this.AllShoppingCartModel.ShoppingCartsList = await this.shoppingCartsService.GetAllSingleShoppingCartsOfTheUserAsync(applicationUserId);
                this.AllShoppingCartModel.TotalPrice = this.shoppingCartsService.GetOrderTotalOfShoppingCartsOfTheUser(this.AllShoppingCartModel.ShoppingCartsList);
                this.HttpContext.Session.SetInt32(GlobalConstants.SessionCart, this.AllShoppingCartModel.ShoppingCartsList.Count);
            }

            this.TempData["Domain"] = this.Request.Scheme + "://" + this.Request.Host.Value + "/";
            return this.View(this.AllShoppingCartModel);
        }

        [HttpPost]
        [ActionName("Index")]
        public async Task<IActionResult> IndexPost()
        {
            var applicationUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!string.IsNullOrEmpty(applicationUserId))
            {
                this.AllShoppingCartModel.ShoppingCartsList = await this.shoppingCartsService.GetAllSingleShoppingCartsOfTheUserAsync(applicationUserId);
                this.AllShoppingCartModel.TotalPrice = this.shoppingCartsService.GetOrderTotalOfShoppingCartsOfTheUser(this.AllShoppingCartModel.ShoppingCartsList);
            }

            try
            {
                await this.ordersService.AddOrderAsync(this.AllShoppingCartModel, applicationUserId);
                this.HttpContext.Session.Clear();
                this.TempData["Message"] = "Order placed successfully";
            }
            catch (Exception)
            {
                this.ModelState.AddModelError(string.Empty, "You can not place an order without dishes");
                return this.View(this.AllShoppingCartModel);
            }

            return this.RedirectToAction("MyOrders", "Orders");
        }

        public async Task<IActionResult> Minus(int shoppingCartId)
        {
            await this.shoppingCartsService.DecreaseQuantityOfTheDishInTheShoppingCart(shoppingCartId);
            return this.RedirectToAction(nameof(this.Index));
        }

        public async Task<IActionResult> Plus(int shoppingCartId)
        {
            await this.shoppingCartsService.IncreaseQuantityOfTheDishInTheShoppingCart(shoppingCartId);
            return this.RedirectToAction(nameof(this.Index));
        }

        public async Task<IActionResult> Remove(int shoppingCartId)
        {
            await this.shoppingCartsService.RemoveDishFromTheShoppingCart(shoppingCartId);
            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/MyHotelWebsite.Web/Areas/Guest/Views/ShoppingCarts/Buy.cshtml
@using Microsoft.AspNetCore.Identity;
@using MyHotelWebsite.Common;
@using MyHotelWebsite.Data.Models;
@using MyHotelWebsite.Web.ViewModels.Guests.ShoppingCarts;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@model SingleShoppingCartViewModel

<body>
    <form method="post">
        <input type="hidden" asp-for="@Model.DishId"/>
        <input type="hidden" asp-for="@Model.ApplicationUserId"/>
        <div class="row">
            <div class="col-10 offset-1">
                <div class="card mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-6">
                            <img src="@(this.TempData["Domain"] + @Model.Dish.DishImageUrl)" alt="@Model.Dish.Name" class="card-img">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <h2 class="card-title text-center mb-4">@Model.Dish.Name</h2>
                                <h3 class="card-text mb-3"><b>Category: </b>@Model.Dish.DishCategory</h3>
                                <h3 class="card-text mb-3"><b>Price: </b>@Model.Dish.Price euro</h3>
                                @if (this.SignInManager.IsSignedIn(this.User) && this.User.IsInRole(GlobalConstants.GuestRoleName))
                                {
                                    <br />
                                    <br />
                                    <div asp-validation-summary="All" class="text-danger"></div>
                                    <div class="d-flex justify-content-center mb-4">
                                        <div class="form-outline me-4" style="width:200px">
                                            <label class="mb-3" asp-for="@Model.Count" style="font-size:large">Count:</label>
                                            <input asp-for="@Model.Count" type="number" class="form-control" />
                                            <span asp-validation-for="@Model.Count" class="text-danger"></span>
                                        </div>
                                        <button type="submit" class="btn btn-small btn-danger" style="margin-right:10px; width:150px" asp-route-id="@Model.Dish.Id" class="btn btn-secondary">Add to cart</button>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Web/MyHotelWebsite.Web/Areas/Guest/Views/ShoppingCarts/Index.cshtml
@using MyHotelWebsite.Web.ViewModels.Guests.ShoppingCarts;

@{
    Layout = null;
}

@model AllShoppingCartsOfOneUserViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping Cart</title>
    
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/font-awesome/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/css/shoppingCart.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" asp-append-version="true" />
</head>
<body>
<form method="post">
        <div class="container px-3 my-5 clearfix">
            <!-- Shopping cart table -->
            <div class="card mt-3">
                <div class="card-header text-danger text-center pt-3 mb-3" style="color:#d9534f">
                    <partial name="_Notification" />
                    <h2><b>Shopping Cart</b></h2>
                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered m-0">
                            <thead>
                                <tr>
                                    <!-- Set columns width -->
                                    <th class="text-center py-3 px-4" style="min-width:300px;font-size:24px">Dish Name &amp; Details</th>
                                    <th class="text-right py-3 px-4" style="width:80px;font-size:18px">Price (euro)</th>
                                    <th class="text-center py-3 px-4" style="width:50px;font-size:18px">Quantity</th>
                                    <th class="text-center py-3 px-4" style="width:80px;font-size:18px">Add / Subtract</th>
                                    <th class="text-center py-3 px-4" style="width:80px;font-size:18px">Total (euro)</th>
                                    <th class="text-center align-middle py-3 px-0" style="width:80px;font-size:18px">Remove</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var singleShoppingCart in Model.ShoppingCartsList)
                                {
                                    <tr>
                                        <td id="name-and-category-div">
                                            <img src="@( this.TempData["Domain"] + singleShoppingCart.Dish.DishImageUrl)" alt="@singleShoppingCart.Dish.Name">
                                            <div id="divs-heading">
                                                <h3 id="h3" class="text-danger"><b>@singleShoppingCart.Dish.Name</b></h3>
                                                <h4 id="h4" class="text-danger">
                                                    <b>
                                                        Category:
                                                    </b> @singleShoppingCart.Dish.DishCategory
                                                </h4>
                                            </div>
                                        </td>
                                        <td class="text-right font-weight-semibold align-middle p-4" style="font-size:18px">@singleShoppingCart.Dish.Price</td>
                                        <td class="text-center align-middle px-0" style="font-size:18px">@singleShoppingCart.Count</td>
                                        <td class="text-center font-weight-semibold align-middle p-4" style="font-size:18px"><a asp-area="Guest" asp-controller="ShoppingCarts" asp-action="Plus" asp-route-shoppingCartId="@singleShoppingCart.Id"><i id="plus" class="fa fa-plus-square" aria-hidden="true"></i></a> <a asp-area="Guest" asp-controller="ShoppingCarts" asp-action="Minus" asp-route-shoppingCartId="@singleShoppingCart.Id"><i id="minus" class="fa fa-minus-square" aria-hidden="true"></i></a></td>
                                        <td class="text-center align-middle px-0" style="font-size:16px">@((singleShoppingCart.Dish.Price * singleShoppingCart.Count).ToString("F2"))</td>
                                        <td class="text-center align-middle p-4"><a asp-area="Guest" asp-controller="ShoppingCarts" asp-action="Remove" asp-route-shoppingCartId="@singleShoppingCart.Id"><i id="remove" class="fa fa-times fa-2x" aria-hidden="true"></i></a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- / Shopping cart table -->
                    <div class="d-flex">
                        <div class="text-right mt-4">
                            <span style="font-size:22px"><strong>Total price: @Model.TotalPrice.ToString("F2") </strong>euro</span>
                        </div>
                    </div>
                    <div class="btn-group mb-5" role="group">
                        <a asp-area="" asp-controller="Dishes" asp-action="All" type="button" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">Back to shopping</a>
                        <button type="submit" class="btn btn-lg btn-danger mt-2">Finish the order</button>
                    </div>

                </div>
                <br />
            </div>
        </div>
</form>
    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }

    <script src="http://code.jquery.com/jquery-1.11.0.min.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
</body>
</html>